answer01.py の最後で軽く触れた
OpenCVの画像の例を表したものです．


In [1]:
import cv2
import numpy as np

width: int = 3
height: int = 5

image = np.zeros((height, width, 3), np.uint8)

for h in range(0, height):
    for w in range(0, width):
        image[h, w] = [128, 64, 32]

print(image)

[[[128  64  32]
  [128  64  32]
  [128  64  32]]

 [[128  64  32]
  [128  64  32]
  [128  64  32]]

 [[128  64  32]
  [128  64  32]
  [128  64  32]]

 [[128  64  32]
  [128  64  32]
  [128  64  32]]

 [[128  64  32]
  [128  64  32]
  [128  64  32]]]
